ARG PYTORCH_IMAGE=nvcr.io/nvidia/pytorch:23.02-py3
FROM ${PYTORCH_IMAGE}

RUN python3 -m pip install -U pip
RUN python3 -m pip install -U setuptools
RUN python3 -m pip install nvflare==2.4.0

WORKDIR /workspace/

ENV PYTHONPATH=$PYTHONPATH:/workspace/app/code/

COPY ./jobs/ /workspace/jobs/
COPY ./app/ /workspace/app/
COPY ./entry_central.py /workspace/entry_central.py
COPY ./entry_edge.py /workspace/entry_edge.py

ENV DATA_DIR=/workspace/data/
ENV RESULTS_DIR=/workspace/results/